-- PRG2, TO INSERT VALUES INTO BUSORG_DET2                              00010000
INSERT INTO busorg_DET2 VALUES('42B','Adayar','Egmore',16,'AC');        00020001
INSERT INTO busorg_DET2 VALUES('A44','Tambaram','Mandaveli',25,'NOR');  00030001
INSERT INTO busorg_DET2 VALUES('T51','Thiruvanmiyur',                   00040001
                             'Tambaram',15,'DX');                       00041000
INSERT INTO busorg_DET2 VALUES('R22','Broadway','Ramapuram',20,'UDX');  00050001
INSERT INTO busorg_DET2 VALUES('7H','Anna Nagar','Parrys',25,'DX');     00060001
INSERT INTO busorg_DET2 VALUES('A63','Mambalam','Triplicane',20,'DX');  00070001
