--INSERT INTO COURSE_REG2                                               00010005
--VALUES('CR001','BTECH-IT','AP001','NARMADHA',17,'F',62.00,'ACP');     00020005
INSERT INTO COURSE_REG2                                                 00030005
VALUES('CR001','BTECH-IT','AP006','NIRMALA',20,'F',50.00,'REJ');        00040006
INSERT INTO COURSE_REG2                                                 00050005
VALUES('CR001','BTECH-IT','AP015','ARPITHA',18,'F',75.50,'ACP');        00060006
INSERT INTO COURSE_REG2                                                 00070005
VALUES('CR001','BTECH-CSE','AP003','SUBRATHA',19,'F',65.50,'ACP');      00080006
INSERT INTO COURSE_REG2                                                 00090005
VALUES('CR001','BTECH-CSE','AP005','ARUNA',18,'F',50.00,'REJ');         00100006
INSERT INTO COURSE_REG2                                                 00110005
VALUES('CR001','BTECH-CSE','AP012','BHUVANA',20,'F',80.75,'ACP');       00120006
