insert into busorg  values('42B',16,'AC');                              00010002
insert into busorg  values('21h',15,'AC');                              00020002
insert into busorg  values('A44',25,'NOR');                             00030002
insert into busorg  values('R22',20,'AC');                              00040002
insert into busorg  values('42C',10,'AC');                              00050002
insert into busorg  values('A63',20,'AC');                              00060002
 -----------------  INSERT INTO TAB 2  -----------------                00070000
insert into bus  values('42B','Adyar','Egmore',null);                   00080002
insert into bus  values('21H','Kelambakkam','Broadway',30.50);          00090002
insert into bus  values('A44','Tambaram','Mandaveli',06.50);            00100002
insert into bus  values('R22','Broadway','Ramapuram',10.50);            00110002
insert into bus  values('42C','K K Nagar','T nagar',25.00);             00120002
insert into bus  values('A63','Mambalam','Triplicane',08.00);           00130002
