insert into busorg_det2 values('42B',16,'AC');                          00010001
insert into busorg_det2 values('21h',15,'AC');                          00020001
insert into busorg_det2 values('A44',25,'NOR');                         00030001
insert into busorg_det2 values('R22',20,'AC');                          00040001
insert into busorg_det2 values('42C',10,'AC');                          00050001
insert into busorg_det2 values('A63',20,'AC');                          00060001
 -----------------  INSERT INTO TAB 2  -----------------                00070000
insert into bus_det2 values('42B','Adyar','Egmore',20.00);              00080001
insert into bus_det2 values('21H','Kelambakkam','Broadway',30.50);      00090001
insert into bus_det2 values('A44','Tambaram','Mandaveli',06.50);        00100001
insert into bus_det2 values('R22','Broadway','Ramapuram',10.50);        00110001
insert into bus_det2 values('42C','K K Nagar','T nagar',25.00);         00120001
insert into bus_det2 values('A63','Mambalam','Triplicane',08.00);       00130001
