insert into tb_employee values (1111,'DINESH','CHENNAI');               00010000
insert into tb_employee values (1112,'BALAJI','MUMBAI');                00020000
insert into tb_employee values (1113,'SHAAM','KOLKATA');                00030000
insert into tb_employee values (1114,'ABDUL','CALICUT');                00040000
insert into tb_employee values (1117,'AARTHY','CALICUT');               00050000
