 -- SPUFI FOR DOC 1 Q1, INSERT VALUES INTO TABLE 1                      00001003
--INSERT INTO COURSE_REG2 VALUES('CR001','B.TECH - IT','AP001',         00010003
--                       'NARMADHA',17,'F',62.00,'ACP');                00020003
  INSERT INTO COURSE_REG2 VALUES('CR001','B.TECH - IT','AP006',         00030003
                         'NIRMALA',20,'F',50.00,'REJ');                 00040003
  INSERT INTO COURSE_REG2 VALUES('CR001','B.TECH - IT','AP015',         00050003
                         'ARPHITHA',18,'F',75.00,'ACP');                00060003
  INSERT INTO COURSE_REG2 VALUES('CR002','B.TECH - CSE','AP003',        00070003
                         'SUBHATHRA',19,'F',65.50,'ACP');               00080003
  INSERT INTO COURSE_REG2 VALUES('CR002','B.TECH - CSE','AP005',        00090003
                         'ARUNA',18,'F',50.00,'REJ');                   00100003
  INSERT INTO COURSE_REG2 VALUES('CR002','B.TECH - CSE','AP012',        00110003
                         'BHUVANA',20,'F',80.75,'ACP');                 00120003
