 -- SPUFI FOR DOC 1 Q1, INSERT VALUES INTO TABLE 2                      00010000
 -- INSERT INTO dept_alot2(dept_id,course_name2,cls_id,room_no,cls_tot) 00020002
                                                                        00020101
--  VALUES('dp001','B.TECH - IT','cls01',                               00021002
  --                       10,2035);                                    00030002
 -- INSERT INTO dept_alot2(dept_id,course_name2,cls_id,room_no,cls_tot) 00040002
 -- VALUES('dp002','B.TECH - cse','cls01',                              00041002
  ---                               15,2500);                           00050002
