INSERT INTO MASTER_ACCT VALUES('FRANCIS','CHENNAI','ACCTBAL1',          00010000
                                8939477777,'A');                        00020000
INSERT INTO MASTER_ACCT VALUES('NEERAJA','MUMBAI','ACCTBAL2',           00030000
                                9999999999,'I');                        00040000
INSERT INTO MASTER_ACCT VALUES('MIKE','CHENNAI','ACCTBAL3',             00050000
                                8888888888,'A');                        00060000
INSERT INTO MASTER_ACCT VALUES('CHAN','KOLKATA','ACCTBAL4',             00070000
                                7777777777,'A');                        00080000
INSERT INTO MASTER_ACCT VALUES('FEDRICK',NULL,'ACCTBAL5',               00090000
                                8939477777,'A');                        00100000
INSERT INTO ACCT_TABLE VALUES('ACCTBAL1','SA','2010-02-01',20000,20000, 00110001
                              'ONLINE','CHENNAI','P');                  00120000
INSERT INTO ACCT_TABLE VALUES('ACCTBAL2','CA','2010-02-01',29000,29000, 00130001
                              'MOBILE','MUMBAI','L');                   00140000
INSERT INTO ACCT_TABLE VALUES('ACCTBAL3','CA','2010-02-01',15000,15000, 00150001
                              'MOBILE','MUMBAI','P');                   00160000
