-- insert values into safe_bank2                                        00010000
-- **********************************                                   00020000
   INSERT INTO SAFE_BANK2 VALUES(100656003,'SAV');                      00030000
   INSERT INTO SAFE_BANK2 VALUES(100424007,'CUR');                      00040000
   INSERT INTO SAFE_BANK2 VALUES(100646003,'SAV');                      00050000
   INSERT INTO SAFE_BANK2 VALUES(100626003,'SAV');                      00060000
-- ***********************************************************          00070000
-- INSERT VALUES INTO CUST_DET2                                         00080000
-- *********************************                                    00090000
   INSERT INTO CUST_DET2 VALUES(100656003,'JOHN','TN');                 00100000
   INSERT INTO CUST_DET2 VALUES(100424007,'MIKE','AP');                 00110000
   INSERT INTO CUST_DET2 VALUES(100646003,'STEVE','TN');                00120000
   INSERT INTO CUST_DET2 VALUES(100626003,'MULLER','KR');               00130000
-- ***********************************************************          00140000
-- INSERT VALUES INTO ST_DET2                                           00150000
-- *********************************                                    00160000
   INSERT INTO ST_DET2 VALUES('TN','TAMILNADU');                        00170000
   INSERT INTO ST_DET2 VALUES('AP','ANDHRAPRADESH');                    00180000
   INSERT INTO ST_DET2 VALUES('KR','KARNATAKA');                        00190000
   INSERT INTO ST_DET2 VALUES('KE','KERALA');                           00200000
